services:
  api:
    build: ./api
    ports:
      - "8000:8000"
      - "8089:8089"  # Pour l'interface Locust (temporaire)
    volumes:
      - ./api:/app
    environment:
      - MODEL_PATH=/app/app/model/segmentation_model.keras  # Chemin du modèle

  web:
    build: ./webapp
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app
      - ../data:/app/data  # Montage du dossier data de la machine hôte dans /app/data du conteneur
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict  # Communication entre les services
      - PYTHONUNBUFFERED=1 # Exécution en mode non bufferisé
